name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up GTK
      run: |
        apt-get update
        apt-get install -y libgtk-3-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
